name: stomach_ache_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.18.4 <3.0.0"
dependencies:
  table_calendar: ^3.0.8
  intl: ^0.17.0
  flutter_riverpod: ^2.1.1
  share_plus: ^6.3.0
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter_native_splash:
  image: "assets/splash.png"
  color: "#008080"
  fullscreen: true
